basic:
    name: 'https://xnpartners.com/'
    environments:
        production: 'https://xnpartners.com/'
        staging: ''
        development: ''
    basicAuth:
        production: { user: '', password: '' }
        staging: { user: '', password: '' }
        development: null
    breakpoints:
        - 640
        - 1024
        - 1200
    pages:
        - /
        - /capacitaciones
        - /blog
        - /tienda
        - /consultoria
        - /conferencia
    monitoring:
        days: [Thu, Wed]
        type: weekly
        schedule_time: '12:30 AM'
        schedule_time_zone: America/Montevideo
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: ''
    remove: ''
    delay: 15
    scroll: true
    headers:
        - { header: '', value: '' }
    cookies: ''
    custom_js: ''
    custom_css: ''
    mock_content: ''
    sensitivity: 15
    night_mode: false
    retina_images: false
    single_ip: false
    performance:
        workers_production: 30
        workers_nonproduction: 10
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: true
